services:
  command:
    image: homepi-command:latest
    # when running local, have the service auto-start
    deploy:
      replicas: 1

  run:
    image: homepi-command:latest

  run_local:
    image: homepi-command:latest

  pull:
    image: homepi-command:latest

  reset:
    image: homepi-command:latest
 